In [1]:
from utilities import *

In [2]:
import joblib
import tensorflow as tf

In [3]:
ble = read_ble('../Data/ble.csv')

In [4]:
rssi = pd.read_csv('../Data/sequenceRssi.csv')

In [5]:
rssi = rssi.pivot_table(columns="scanner", values="rssi", index="time")
rssi.rename_axis(None, axis=1, inplace=True)
rssi.index = pd.to_datetime(rssi.index)

In [6]:
rssi = rssi.groupby(pd.Grouper(freq='100ms')).mean()
rssi

,C400A2E19293,CD4533FFC0E1,D2B6503554D7,DB8B36A69C56,DD697EA75B68,DF231643E227,E13B805C6CB0,E43355CA8B96,E6D9D20DD197,E8FD0B453DC4,E96AF2C858BA,EC72840D9AD3,F1307ECB3B90,F1EDAF28E08A,F69A86823B96,FB2EE01C18CE,FDAE5980F28C
time,,,,,,,,,,,,,,,,,
2020-01-03 03:20:13.500,NaN,NaN,NaN,-77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03 03:20:13.600,NaN,NaN,NaN,NaN,NaN,-64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03 03:20:13.700,NaN,NaN,NaN,NaN,NaN,-63.0,NaN,NaN,-74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03 03:20:13.800,NaN,NaN,NaN,NaN,NaN,NaN,-65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03 03:20:13.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-03 03:21:19.000,NaN,-70.0,NaN,NaN,NaN,NaN,-76.0,NaN,NaN,NaN,-77.0,-69.0,NaN,NaN,NaN,-91.0,-82.0
2020-01-03 03:21:19.100,NaN,-66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-79.0,NaN,NaN
2020-01-03 03:21:19.200,NaN,-66.0,-78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-68.0,NaN,NaN,-77.0,NaN,-80.0
2020-01-03 03:21:19.300,NaN,NaN,NaN,-83.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-70.0,-68.0,NaN,-66.0,NaN,-84.0
2020-01-03 03:21:19.400,NaN,-67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
loc = pd.read_csv('../Data/sequenceLoc.csv')
loc['time'] = pd.to_datetime(loc['time'])
loc.set_index('time', inplace=True)

In [8]:
loc = loc.groupby(pd.Grouper(freq='100ms')).mean()
loc.ffill(inplace=True)
loc

                                X         Y
time
2020-01-03 03:20:17.800  0.913984  3.540312
2020-01-03 03:20:17.900  0.878266  3.491532
2020-01-03 03:20:18.000  0.878266  3.491532
2020-01-03 03:20:18.100  0.905576  3.362762
2020-01-03 03:20:18.200  0.932652  3.274408
...                           ...       ...
2020-01-03 03:21:19.000  1.115414  3.595589
2020-01-03 03:21:19.100  1.130193  3.584988
2020-01-03 03:21:19.200  1.143236  3.564371
2020-01-03 03:21:19.300  1.145016  3.552412
2020-01-03 03:21:19.400  1.131611  3.536157

[617 rows x 2 columns]

In [9]:
def transform(loc, inplace=False):
    if inplace:
        loc['X'] = 24.187023 + loc['X']
        loc['Y'] = 12.252072 - loc['Y']
    else:
        transformed = pd.DataFrame()
        transformed['X'] = 24.187023 + loc['X']
        transformed['Y'] = 12.252072 - loc['Y']
        return transformed

In [10]:
transform(loc, inplace=True)
loc

                                 X         Y
time
2020-01-03 03:20:17.800  25.101007  8.711760
2020-01-03 03:20:17.900  25.065289  8.760540
2020-01-03 03:20:18.000  25.065289  8.760540
2020-01-03 03:20:18.100  25.092599  8.889310
2020-01-03 03:20:18.200  25.119675  8.977664
...                            ...       ...
2020-01-03 03:21:19.000  25.302437  8.656483
2020-01-03 03:21:19.100  25.317216  8.667084
2020-01-03 03:21:19.200  25.330259  8.687701
2020-01-03 03:21:19.300  25.332039  8.699659
2020-01-03 03:21:19.400  25.318634  8.715915

[617 rows x 2 columns]

In [11]:
data = rssi.join(loc, how='inner')
data.shape

(617, 19)

In [12]:
data = data[:-7]
data

,C400A2E19293,CD4533FFC0E1,D2B6503554D7,DB8B36A69C56,DD697EA75B68,DF231643E227,E13B805C6CB0,E43355CA8B96,E6D9D20DD197,E8FD0B453DC4,E96AF2C858BA,EC72840D9AD3,F1307ECB3B90,F1EDAF28E08A,F69A86823B96,FB2EE01C18CE,FDAE5980F28C,X,Y
time,,,,,,,,,,,,,,,,,,,
2020-01-03 03:20:17.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.0,NaN,NaN,NaN,NaN,-88.0,NaN,25.101007,8.711760
2020-01-03 03:20:17.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.065289,8.760540
2020-01-03 03:20:18.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.065289,8.760540
2020-01-03 03:20:18.100,NaN,NaN,NaN,NaN,NaN,NaN,-71.0,NaN,NaN,NaN,-69.0,NaN,NaN,NaN,-82.5,NaN,NaN,25.092599,8.889310
2020-01-03 03:20:18.200,NaN,NaN,NaN,NaN,NaN,-68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-88.0,NaN,NaN,25.119675,8.977664
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-03 03:21:18.300,NaN,NaN,-82.0,NaN,NaN,NaN,NaN,NaN,-72.5,NaN,NaN,NaN,NaN,NaN,NaN,-84.0,NaN,25.290861,8.694452
2020-01-03 03:21:18.400,NaN,NaN,NaN,NaN,NaN,-62.0,NaN,NaN,NaN,NaN,-87.0,NaN,NaN,NaN,NaN,NaN,NaN,25.302390,8.706907
2020-01-03 03:21:18.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.0,NaN,-75.0,NaN,NaN,NaN,NaN,NaN,NaN,25.301330,8.708440
2020-01-03 03:21:18.600,NaN,NaN,NaN,NaN,NaN,-60.0,-75.0,NaN,NaN,NaN,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,25.301536,8.588901
2020-01-03 03:21:18.700,NaN,-70.0,NaN,NaN,NaN,-62.0,NaN,NaN,-82.0,NaN,NaN,-68.0,NaN,NaN,NaN,-94.0,-94.0,25.303901,8.626267

In [13]:
def impute(data):
    data[scanners] = min_max_scaling(data[scanners])
    data.update(data.rolling('1s').mean())
    data.ffill(inplace=True)

In [14]:
def reg_impute(data):
    for s in scanners:
        dx = data['X'] - ble[s]['X']
        dy = data['Y'] - ble[s]['Y']
        d = np.sqrt(np.square(dy) + np.square(dx))
        reg = joblib.load('../Models/linear_distance_models/{}.joblib'.format(s))
        ss = pd.Series(reg.predict(d.values.reshape((-1, 1))))
        ss.index = data.index
        data[s].fillna(ss, inplace=True)

In [15]:
impute(data)
reg_impute(data)

In [16]:
data.describe()

,C400A2E19293,CD4533FFC0E1,D2B6503554D7,DB8B36A69C56,DD697EA75B68,DF231643E227,E13B805C6CB0,E43355CA8B96,E6D9D20DD197,E8FD0B453DC4,E96AF2C858BA,EC72840D9AD3,F1307ECB3B90,F1EDAF28E08A,F69A86823B96,FB2EE01C18CE,FDAE5980F28C,X,Y
count,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000
mean,0.307196,0.421528,0.333240,0.432965,0.395507,0.403917,0.341602,0.299325,0.241999,0.235881,0.283829,0.468927,0.469234,0.267792,0.378696,0.215848,0.294545,20.351089,6.267206
std,0.116921,0.141461,0.087104,0.131874,0.075015,0.145457,0.124366,0.141063,0.119050,0.100219,0.115101,0.111669,0.120582,0.159167,0.158276,0.066954,0.076988,3.443166,1.159442
min,0.100000,0.150000,0.100000,0.158333,0.183333,0.100000,0.100000,0.100000,0.100000,0.083333,0.083333,0.250000,0.166667,0.066667,0.066667,0.100000,0.083333,10.415149,5.231669
25%,0.216667,0.333333,0.300000,0.300935,0.383333,0.316667,0.266667,0.200693,0.150000,0.183333,0.200000,0.400000,0.400000,0.166667,0.250000,0.183333,0.266667,18.838964,5.636624
50%,0.283333,0.450000,0.333333,0.466667,0.383333,0.433333,0.333333,0.233333,0.216667,0.233333,0.283333,0.466667,0.483333,0.216667,0.383333,0.200000,0.266667,19.042845,5.657075
75%,0.383333,0.533333,0.383333,0.533333,0.416667,0.500000,0.433333,0.400000,0.333333,0.283333,0.375000,0.533333,0.562500,0.350000,0.500000,0.216667,0.350000,23.118554,6.101789
max,0.566667,0.700000,0.533333,0.700000,0.550000,0.700000,0.575000,0.650000,0.533333,0.416667,0.511111,0.716667,0.666667,0.666667,0.750000,0.466667,0.494444,25.314814,9.085981

In [17]:
def create_window(dataset, win_size, start_index=0, end_index=None):
    data = []
    labels = []

    start_index = start_index + win_size
    if end_index is None:
        end_index = len(dataset)

    for i in range(start_index, end_index):
        indices = range(i-win_size, i)
        data.append(dataset[scanners].iloc[indices].values)
        labels.append(dataset[['X', 'Y']].iloc[i].values)
    return np.array(data), np.array(labels)

In [18]:
epochs = 4000
batch_size = 32

model = tf.keras.Sequential([
    tf.keras.layers.LSTM(10, activation='relu', input_shape=(10, 17)),
    tf.keras.layers.Dense(2)
])

optimizer = tf.keras.optimizers.RMSprop(0.001)
model.compile(optimizer=optimizer, loss='mse')

In [19]:
X_train, y_train = create_window(data, 10)

In [20]:
dt = tf.data.Dataset.from_tensor_slices((X_train, y_train))
dt = dt.batch(batch_size)

In [ ]:
model.fit(dt, epochs=epochs)

Epoch 1/4000
19/19 [==============================] - 2s 105ms/step - loss: 238.9842
Epoch 2/4000
19/19 [==============================] - 0s 5ms/step - loss: 227.1910
Epoch 3/4000
19/19 [==============================] - 0s 4ms/step - loss: 225.0282
Epoch 4/4000
19/19 [==============================] - 0s 3ms/step - loss: 223.5550
Epoch 5/4000
19/19 [==============================] - 0s 3ms/step - loss: 221.8668
Epoch 6/4000
19/19 [==============================] - 0s 3ms/step - loss: 219.5129
Epoch 7/4000
19/19 [==============================] - 0s 3ms/step - loss: 216.5563
Epoch 8/4000
19/19 [==============================] - 0s 3ms/step - loss: 213.5693
Epoch 9/4000
19/19 [==============================] - 0s 3ms/step - loss: 210.7282
Epoch 10/4000
19/19 [==============================] - 0s 3ms/step - loss: 207.8844
Epoch 11/4000
19/19 [==============================] - 0s 3ms/step - loss: 204.9554
Epoch 12/4000
19/19 [==============================] - 0s 3ms/step - loss: 201.8831
Epoch 13/4000
19/19 [==============================] - 0s 3ms/step - loss: 198.6150
Epoch 14/4000
19/19 [==============================] - 0s 3ms/step - loss: 195.1050
Epoch 15/4000
19/19 [==============================] - 0s 3ms/step - loss: 191.3113
Epoch 16/4000
19/19 [==============================] - 0s 3ms/step - loss: 187.2014
Epoch 17/4000
19/19 [==============================] - 0s 3ms/step - loss: 182.7478
Epoch 18/4000
19/19 [==============================] - 0s 3ms/step - loss: 177.9275
Epoch 19/4000
19/19 [==============================] - 0s 3ms/step - loss: 172.7242
Epoch 20/4000
19/19 [==============================] - 0s 3ms/step - loss: 167.1336
Epoch 21/4000
19/19 [==============================] - 0s 3ms/step - loss: 161.1565
Epoch 22/4000
19/19 [==============================] - 0s 3ms/step - loss: 154.7935
Epoch 23/4000
19/19 [==============================] - 0s 3ms/step - loss: 148.0501
Epoch 24/4000
19/19 [==============================] - 0s 3ms/step - loss: 140.9385
Epoch 25/4000
19/19 [==============================] - 0s 3ms/step - loss: 133.4749
Epoch 26/4000
19/19 [==============================] - 0s 3ms/step - loss: 125.6577
Epoch 27/4000
19/19 [==============================] - 0s 3ms/step - loss: 117.3911
Epoch 28/4000
19/19 [==============================] - 0s 3ms/step - loss: 108.3431
Epoch 29/4000
19/19 [==============================] - 0s 3ms/step - loss: 96.6662
Epoch 30/4000
19/19 [==============================] - 0s 3ms/step - loss: 62.5275
Epoch 31/4000
19/19 [==============================] - 0s 3ms/step - loss: 19.4352
Epoch 32/4000
19/19 [==============================] - 0s 3ms/step - loss: 11.4384
Epoch 33/4000
19/19 [==============================] - 0s 3ms/step - loss: 10.8160
Epoch 34/4000
19/19 [==============================] - 0s 3ms/step - loss: 10.6043
Epoch 35/4000
19/19 [==============================] - 0s 3ms/step - loss: 10.4169
Epoch 36/4000
19/19 [==============================] - 0s 3ms/step - loss: 10.2356
Epoch 37/4000
19/19 [==============================] - 0s 3ms/step - loss: 10.0570
Epoch 38/4000
19/19 [==============================] - 0s 3ms/step - loss: 9.8815
Epoch 39/4000
19/19 [==============================] - 0s 3ms/step - loss: 9.7080
Epoch 40/4000
19/19 [==============================] - 0s 3ms/step - loss: 9.5368
Epoch 41/4000
19/19 [==============================] - 0s 3ms/step - loss: 9.3680
Epoch 42/4000
19/19 [==============================] - 0s 3ms/step - loss: 9.2012
Epoch 43/4000
19/19 [==============================] - 0s 3ms/step - loss: 9.0353
Epoch 44/4000
19/19 [==============================] - 0s 3ms/step - loss: 8.8721
Epoch 45/4000
19/19 [==============================] - 0s 3ms/step - loss: 8.7121
Epoch 46/4000
19/19 [==============================] - 0s 3ms/step - loss: 8.5534
Epoch 47/4000
18/19 [===========================>..] - ETA: 0s - loss: 8.4079

In [ ]:
model.save("../Models/LSTM_basic.h5")